# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UpdateServiceNowChangeRequest@2
  inputs:
    ServiceNowConnection: 'SNOW connection'
    ChangeRequestNumber: 'CHG0400016'
    NewStatus: '0'
    WorkNotes: 'Note 1'
    otherParameters: |
      "cmdb_ci": {
            "display_value": "Globex Prod Web Service",
            "value": "fc3df85e1b58d014673a7733cd4bcbb0"
          }